// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/dolar-y-monedas-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"blue | bolsa | brl | clp | contadoconliqui | cotizacion_ambito | cotizacione | cripto | dolare | estado | eur | mayorista | oficial | tarjeta | uyu"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.DolarYMonedasSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "dolar-y-monedas_list",
		Description: "List records from DolarYMonedas. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "dolar-y-monedas_load",
		Description: "Load a single record from DolarYMonedas. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.DolarYMonedasSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.DolarYMonedasSDK, name string) (sdk.DolarYMonedasEntity, error) {
	switch strings.ToLower(name) {
	case "blue":
		return client.Blue(nil), nil
	case "bolsa":
		return client.Bolsa(nil), nil
	case "brl":
		return client.Brl(nil), nil
	case "clp":
		return client.Clp(nil), nil
	case "contadoconliqui":
		return client.Contadoconliqui(nil), nil
	case "cotizacion_ambito":
		return client.CotizacionAmbito(nil), nil
	case "cotizacione":
		return client.Cotizacione(nil), nil
	case "cripto":
		return client.Cripto(nil), nil
	case "dolare":
		return client.Dolare(nil), nil
	case "estado":
		return client.Estado(nil), nil
	case "eur":
		return client.Eur(nil), nil
	case "mayorista":
		return client.Mayorista(nil), nil
	case "oficial":
		return client.Oficial(nil), nil
	case "tarjeta":
		return client.Tarjeta(nil), nil
	case "uyu":
		return client.Uyu(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
