<?php
declare(strict_types=1);

// DolarYMonedas SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

DolarYMonedasUtility::setRegistrar(function (DolarYMonedasUtility $u): void {
    $u->clean = [DolarYMonedasClean::class, 'call'];
    $u->done = [DolarYMonedasDone::class, 'call'];
    $u->make_error = [DolarYMonedasMakeError::class, 'call'];
    $u->feature_add = [DolarYMonedasFeatureAdd::class, 'call'];
    $u->feature_hook = [DolarYMonedasFeatureHook::class, 'call'];
    $u->feature_init = [DolarYMonedasFeatureInit::class, 'call'];
    $u->fetcher = [DolarYMonedasFetcher::class, 'call'];
    $u->make_fetch_def = [DolarYMonedasMakeFetchDef::class, 'call'];
    $u->make_context = [DolarYMonedasMakeContext::class, 'call'];
    $u->make_options = [DolarYMonedasMakeOptions::class, 'call'];
    $u->make_request = [DolarYMonedasMakeRequest::class, 'call'];
    $u->make_response = [DolarYMonedasMakeResponse::class, 'call'];
    $u->make_result = [DolarYMonedasMakeResult::class, 'call'];
    $u->make_point = [DolarYMonedasMakePoint::class, 'call'];
    $u->make_spec = [DolarYMonedasMakeSpec::class, 'call'];
    $u->make_url = [DolarYMonedasMakeUrl::class, 'call'];
    $u->param = [DolarYMonedasParam::class, 'call'];
    $u->prepare_auth = [DolarYMonedasPrepareAuth::class, 'call'];
    $u->prepare_body = [DolarYMonedasPrepareBody::class, 'call'];
    $u->prepare_headers = [DolarYMonedasPrepareHeaders::class, 'call'];
    $u->prepare_method = [DolarYMonedasPrepareMethod::class, 'call'];
    $u->prepare_params = [DolarYMonedasPrepareParams::class, 'call'];
    $u->prepare_path = [DolarYMonedasPreparePath::class, 'call'];
    $u->prepare_query = [DolarYMonedasPrepareQuery::class, 'call'];
    $u->graphql_body = [DolarYMonedasGraphql::class, 'body'];
    $u->graphql_errors = [DolarYMonedasGraphql::class, 'errors'];
    $u->result_basic = [DolarYMonedasResultBasic::class, 'call'];
    $u->result_body = [DolarYMonedasResultBody::class, 'call'];
    $u->result_headers = [DolarYMonedasResultHeaders::class, 'call'];
    $u->transform_request = [DolarYMonedasTransformRequest::class, 'call'];
    $u->transform_response = [DolarYMonedasTransformResponse::class, 'call'];
});
